### ISSUE TITLE
Is there a way to use python venv ?

### ISSUE THREAD

**Issue by sharat9211** [jswh/wslexe#6]
I used this for using wsl python in vscode. It works smoothly. Kudos!! But I could not figure out a way to make it work with python virtual environments created in WSL. Is it possible or can we figure out a way to achieve this?

**Comment by jswh** [comment]
I am working on this issue https://github.com/jswh/wslexe/issues/5.
This will solve the proplem in my mind.

**Comment by sharat9211** [comment]
Yes, it should. Thanks!

**Comment by jswh** [comment]
https://github.com/jswh/wslexe/pull/7
I have tried to set GOROOT and GOPATH with `.wslexerc` .
Would you please download the new version and have a try for python venv?

**Comment by sharat9211** [comment]
I wslexe zip.It also contains wslexe_i. What is its purpose?

**Comment by sharat9211** [comment]
I am able to activate virtual environments. Thanks

**Comment by jswh** [comment]
wslexe_i execute command as `bash -ic`
